package org.usvm.machine.interpreter.transformers.SpringJPA

import kotlinx.collections.immutable.toPersistentList
import org.jacodb.api.jvm.JcClassExtFeature
import org.jacodb.api.jvm.JcClassOrInterface
import org.jacodb.api.jvm.JcClasspath
import org.jacodb.api.jvm.JcField
import org.jacodb.api.jvm.JcMethod
import org.jacodb.api.jvm.ext.findClass
import org.jacodb.api.jvm.ext.jvmName
import org.jacodb.impl.bytecode.JcFieldImpl
import org.jacodb.impl.bytecode.JcMethodImpl
import org.jacodb.impl.cfg.util.internalDesc
import org.jacodb.impl.features.JcFeaturesChain
import org.jacodb.impl.types.*
import org.objectweb.asm.Opcodes
import org.usvm.util.JcTableInfoCollector
import org.usvm.util.Relation
import org.usvm.util.TableInfo
import org.usvm.util.blancAnnotation
import org.usvm.util.contains
import org.usvm.util.getSetFieldName
import org.usvm.util.jvmDescriptor

val JcClassOrInterface.isDataClass: Boolean get() = contains(annotations, "Entity")

const val INIT_ANNOT = "\$generatedInit"
const val GET_ID_ANNOT = "\$generatedGetId"
const val FILTER_ANNOT = "\$generatedFilter"
const val FILTER_BTW_ANNOT = "\$generatedBtwFilter"
const val SELECT_BTW_ANNOT = "\$generatedBtwSelector"
const val FILTER_SET_ANNOT = "\$generatedSetFilter"
const val SERIALIZER_ANNOT = "\$generatedSerializer"
const val IDENTITY_ANNOT = "\$generatedIdent"

// cp.findClass("generated.org.springframework.boot.databases.FirstDataClass")
//"org.springframework.samples.petclinic.vet.Vet"

object TestTransformer : JcClassExtFeature {

    var b : Int = 0
    override fun methodsOf(clazz: JcClassOrInterface): List<JcMethod>? {

        if (clazz.classpath.findClass("SpringDatabases").declaredFields.size == 0 || b == 1) return null

        b++;
        val cp = clazz.classpath
        val foo = cp.findClass("org.springframework.samples.petclinic.owner.OwnerRepository")
        val bar = foo.declaredMethods.find { it.name == "findPetTypes" }!!
        //val bar = foo.declaredMethods.find { it.name == "findById" }!!

        println(bar.instList)

        return null
    }
}

object JcDataclassTransformer : JcClassExtFeature {

    // prevents cycles
    private val askedClasses : HashMap<String, MutableList<JcField>> = hashMapOf()
    // relation - generated by it field
    private val relationFields : HashMap<String, JcField> = hashMapOf()

    private val relationMethods : HashMap<String, List<JcMethod>> = hashMapOf()

    private var collector : JcTableInfoCollector? = null

    fun getCollector() : JcTableInfoCollector {
        return collector!!
    }

    fun initCollector(cp : JcClasspath) : JcTableInfoCollector {
        if (collector == null) collector = JcTableInfoCollector(cp)
        return getCollector()
    }

    fun relatedField(clazz : JcClassOrInterface, field : JcField) : JcField? {
        return relationFields[combName(clazz, field)]
    }

    fun relatedLambda(clazz : JcClassOrInterface, field: JcField) : List<JcMethod>? {
        return relationMethods[combName(clazz, field)]
    }

    fun addRelatedLambdas(clazz : JcClassOrInterface, field : JcField, methods : List<JcMethod>) {
        relationMethods[combName(clazz, field)] = methods
    }

    private fun combName(clazz : JcClassOrInterface, field : JcField) : String {
        return "${clazz.name}\$${field.name}"
    }

    override fun fieldsOf(clazz : JcClassOrInterface, originalFields : List<JcField>) : List<JcField>? {

        if (!clazz.isDataClass) return null
        if (askedClasses.contains(clazz.name)) return askedClasses[clazz.name]

        val fields = originalFields.toMutableList()
        askedClasses[clazz.name] = fields

        val cp = clazz.classpath
        val collector = initCollector(cp)
        val classTable = collector.collectTable(clazz)

        classTable.relations.filterIsInstance<Relation.RelationByTable>().forEach { rel ->
            val subTable = collector.findSubTable(rel.origField)!!
            val subIdType = subTable.idColumn.type.typeName
            val fieldInfo = FieldInfo(
                getSetFieldName(rel),
                "Ljava/util/Set<${subIdType.jvmName()}>;",
                Opcodes.ACC_PUBLIC,
                "Ljava.util.Set;",
                listOf()
            )
            val field = JcFieldImpl(clazz, fieldInfo)
            relationFields[combName(clazz, rel.origField)] = field
            fields.add(field)
        }

        classTable.columns.filter { !it.isOrig }.forEach { col ->
            val subTable = collector.findSubTable(col.origField)!!
            val subIdType = subTable.idColumn.type.typeName
            val fieldInfo = FieldInfo(
                "\$${col.origField.name}IdCheck",
                null,
                Opcodes.ACC_PUBLIC,
                "L${subIdType};",
                listOf()
            )
            val field = JcFieldImpl(clazz, fieldInfo)
            relationFields[combName(clazz, col.origField)] = field
            fields.add(field)
        }

        return fields
    }

    override fun methodsOf(clazz : JcClassOrInterface, originalMethods : List<JcMethod>) : List<JcMethod>? {

        if (!clazz.isDataClass) return null

        val cp = clazz.classpath
        val collector = initCollector(cp)
        val classTable = collector.collectTable(clazz)
        val gen = SignatureGenerator(cp, collector, classTable, originalMethods)

        val blancInit = gen.getConstructor()
        val getId = gen.getId()
        val serializer = gen.getSerializer()
        val lambdas = gen.getLambdas()

        return originalMethods + blancInit + getId + serializer + lambdas
    }
}

private class SignatureGenerator(
    val cp : JcClasspath,
    val collector : JcTableInfoCollector,
    val classTable : TableInfo.TableWithIdInfo,
    val originalMethods : List<JcMethod>
) {

    val clazz = classTable.origClass
    val pFeatures = cp.features!!.toPersistentList()

    fun getConstructor() : JcMethod {

        val origInit = originalMethods.single { it.name == "<init>" && it.parameters.isEmpty() }
        val newFeatures = pFeatures.add(0, JcGeneratedInitTransformer(cp, classTable, origInit))
        val relTables = classTable.orderedRelations()

        val itableDesc = cp.findClass("generated.org.springframework.boot.databases.ITable").jvmDescriptor
        val desc = "([Ljava/lang/Object;${relTables.joinToString(separator = "") { itableDesc }})V"

        val signature = "([Ljava/lang/Object;${relTables.joinToString(separator = "") { rel ->
            "${itableDesc}<${rel.origField.enclosingClass.jvmDescriptor}>"
        }};)V"

        val parametrs = mutableListOf(
            ParameterInfo("java.lang.Object[]", 0, 1, "row", listOf())
        )

        relTables.forEachIndexed { ix, rel ->
            val newParam = ParameterInfo(
                "generated.org.springframework.boot.databases.ITable",
                ix + 1,
                Opcodes.ACC_PUBLIC,
                "${rel}Condition",
                listOf()
            )

            parametrs.add(newParam)
        }

        val newMethodInfo = MethodInfo(
            "<init>",
            desc,
            signature,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(INIT_ANNOT)),
            listOf(),
            parametrs
        )
        val newInit = JcMethodImpl(newMethodInfo, JcFeaturesChain(newFeatures), classTable.origClass)

        return newInit
    }

    fun getId() : JcMethod {

        val newFeatures = pFeatures.add(0, JcGeneratedGetIdTransformer(classTable))
        val desc = "()L${classTable.idColumn.type.internalDesc};"
        val methodInfo = MethodInfo(
            "\$getId",
            desc,
            null,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(GET_ID_ANNOT)),
            listOf(),
            listOf()
        )
        return JcMethodImpl(methodInfo, JcFeaturesChain(newFeatures), classTable.origClass)
    }

    fun getSerializer() : JcMethod {

        val newFeatures = pFeatures.add(0, JcGeneratedSerializerTransformer(classTable))
        val desc = "()[Ljava/lang/Object;"
        val methodInfo = MethodInfo(
            "\$serialize",
            desc,
            null,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(SERIALIZER_ANNOT)),
            listOf(),
            listOf()
        )
        return JcMethodImpl(methodInfo, JcFeaturesChain(newFeatures), classTable.origClass)
    }

    fun getLambdas() : List<JcMethod> {

        val methods = mutableListOf<JcMethod>()

        classTable.relations.forEach { rel ->

            val subTable = collector.findSubTable(rel.origField)!!

            val btwTable = when (rel) {
                is Relation.RelationByTable -> rel.joinTable.name
                else -> null
            }?.let { collector.getBtwTable(it) }

            val newFeature = JcDataclassLambdaTransformer(cp, classTable, subTable, btwTable, rel)
            val newFeatures = JcFeaturesChain(pFeatures.add(0, newFeature))
            val gen = SubSignatureGenerator(rel, subTable, newFeatures, clazz)

            val lambdas = if (rel is Relation.RelationByTable) {
                listOf(gen.getBtwFilter(), gen.getBtwSelector(), gen.getSetFilter())
            }
            else {
                listOf(gen.getFilter())
            }

            JcDataclassTransformer.addRelatedLambdas(clazz, rel.origField, lambdas)
            methods.addAll(lambdas)
        }

        return methods
    }
}

private class SubSignatureGenerator(
    val rel : Relation,
    val subTable : TableInfo.TableWithIdInfo,
    val newFeatures : JcFeaturesChain,
    val clazz: JcClassOrInterface
) {

    fun getFilter() : JcMethod {
        val desc = "(${rel.origField.type.typeName.jvmName()})Ljava/lang/Boolean;"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}filter",
            desc,
            null,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(FILTER_ANNOT)),
            listOf(),
            listOf(ParameterInfo(rel.origField.type.typeName, 0, 1, "subc", listOf()))
        )

        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }

    fun getBtwFilter() : JcMethod {
        val desc = "([Ljava/lang/Object;)Ljava/lang/Boolean;"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}BetweenFilter",
            desc,
            null,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(FILTER_BTW_ANNOT)),
            listOf(),
            listOf(ParameterInfo("java.lang.Object[]", 0, 1, "row", listOf()))
        )
        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }

    fun getBtwSelector() : JcMethod {
        val desc = "([Ljava/lang/Object;)L${subTable.idColumn.type.internalDesc};"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}BetweenSelector",
            desc,
            null,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(SELECT_BTW_ANNOT)),
            listOf(),
            listOf(ParameterInfo("java.lang.Object[]", 0, 1, "row", listOf()))
        )

        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }

    fun getSetFilter() : JcMethod {
        val desc = "(${subTable.origClass.jvmDescriptor})Ljava/lang/Boolean;"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}SetFilter",
            desc,
            null,
            Opcodes.ACC_PUBLIC,
            listOf(blancAnnotation(FILTER_SET_ANNOT)),
            listOf(),
            listOf(ParameterInfo(rel.origField.type.typeName, 0, 1, "subc", listOf()))
        )

        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }
}
