package org.usvm.machine.interpreter.transformers.springjpa

import kotlinx.collections.immutable.persistentListOf
import org.jacodb.api.jvm.JcClassExtFeature
import org.jacodb.api.jvm.JcClassOrInterface
import org.jacodb.api.jvm.JcClasspath
import org.jacodb.api.jvm.JcField
import org.jacodb.api.jvm.JcMethod
import org.jacodb.api.jvm.ext.findClass
import org.jacodb.api.jvm.ext.jvmName
import org.jacodb.api.jvm.ext.toType
import org.jacodb.impl.cfg.util.internalDesc
import org.usvm.util.JcTableInfoCollector
import org.usvm.util.Relation
import org.usvm.util.TableInfo
import org.usvm.util.getSetFieldName
import org.usvm.util.jvmDescriptor


// cp.findClass("generated.org.springframework.boot.databases.FirstDataClass")
//"org.springframework.samples.petclinic.vet.Vet"

object TestTransformer : JcClassExtFeature {

    var b: Int = 0
    override fun methodsOf(clazz: JcClassOrInterface): List<JcMethod>? {

        if (clazz.classpath.findClass("SpringDatabases").declaredFields.size == 0 || b == 1) return null

        b++;
        val cp = clazz.classpath
        val foo = cp.findClass("org.springframework.samples.petclinic.owner.OwnerRepository")
        val bar = foo.declaredMethods.find { it.name == "findPetTypes" }!!
        //val bar = foo.declaredMethods.find { it.name == "findById" }!!

        println(bar.instList)

        return null
    }
}

object JcDataclassTransformer : JcClassExtFeature {

    // prevents cycles
    private val askedClasses: HashMap<String, MutableList<JcField>> = hashMapOf()

    // relation - generated by it field
    private val relationFields: HashMap<String, JcField> = hashMapOf()

    fun relatedField(clazz: JcClassOrInterface, field: JcField): JcField? {
        return relationFields[combName(clazz, field)]
    }

    private val relationMethods: HashMap<String, List<JcMethod>> = hashMapOf()

    fun relatedLambda(clazz: JcClassOrInterface, field: JcField): List<JcMethod>? {
        return relationMethods[combName(clazz, field)]
    }

    fun addRelatedLambdas(clazz: JcClassOrInterface, field: JcField, methods: List<JcMethod>) {
        relationMethods[combName(clazz, field)] = methods
    }

    private fun combName(clazz: JcClassOrInterface, field: JcField): String {
        return "${clazz.name}\$${field.name}"
    }


    override fun fieldsOf(clazz: JcClassOrInterface, originalFields: List<JcField>): List<JcField>? {
        if (!clazz.isDataClass) return null
        if (askedClasses.contains(clazz.name)) return askedClasses[clazz.name]

        val fields = originalFields.toMutableList()
        askedClasses[clazz.name] = fields

        val cp = clazz.classpath
        val collector = JcTableInfoCollector(cp)
        val classTable = collector.collectTable(clazz)

        classTable.relations.filterIsInstance<Relation.RelationByTable>().forEach { rel ->
            val subTable = collector.findSubTable(rel.origField)!!
            val subIdType = subTable.idColumn.type.typeName
            val field = JcFieldBuilder(clazz)
                .setName(getSetFieldName(rel))
                .setSignature("Ljava/util/Set<${subIdType.jvmName()}>;")
                .setType("Ljava.util.Set;")
                .buildField()

            relationFields[combName(clazz, rel.origField)] = field
            fields.add(field)
        }

        classTable.columns.filter { !it.isOrig }.forEach { col ->
            val subTable = collector.findSubTable(col.origField)!!
            val subIdType = subTable.idColumn.type.typeName
            val field = JcFieldBuilder(clazz)
                .setName("\$${col.origField.name}IdCheck")
                .setType("L${subIdType};")
                .buildField()

            relationFields[combName(clazz, col.origField)] = field
            fields.add(field)
        }

        return fields
    }

    override fun methodsOf(clazz: JcClassOrInterface, originalMethods: List<JcMethod>): List<JcMethod>? {
        if (!clazz.isDataClass) return null

        val cp = clazz.classpath
        val collector = JcTableInfoCollector(cp)
        val classTable = collector.collectTable(clazz)
        val gen = SignatureGenerator(cp, collector, classTable, originalMethods)

        return gen.getFunctions()
    }
}

private class SignatureGenerator(
    val cp: JcClasspath,
    val collector: JcTableInfoCollector,
    val classTable: TableInfo.TableWithIdInfo,
    val originalMethods: List<JcMethod>
) {

    val clazz = classTable.origClass

    fun getFunctions(): List<JcMethod> {
        return persistentListOf(getConstructor(), getId(), getSerializer(), getIdentity()).addAll(getLambdas())
    }

    fun getConstructor(): JcMethod {
        val relTables = classTable.orderedRelations()
        val builder = JcMethodBuilder(clazz).setName("<init>").addBlanckAnnot(INIT_ANNOT)

        val origInit = originalMethods.single { it.name == "<init>" && it.parameters.isEmpty() }
        builder.addFillerFuture(JcInitTransformer(cp, classTable, origInit))

        val itableDesc = cp.findClass("generated.org.springframework.boot.databases.ITable").jvmDescriptor

        val desc = "([Ljava/lang/Object;${relTables.joinToString(separator = "") { itableDesc }})V"
        val signature = "([Ljava/lang/Object;${
            relTables.joinToString(separator = "") { rel ->
                "${itableDesc}<${rel.origField.enclosingClass.jvmDescriptor}>"
            }
        };)V"
        builder.setDesc(desc)
        builder.setSignature(signature)

        builder.addFreshParam("java.lang.Object[]")
        relTables.forEach { builder.addFreshParam("generated.org.springframework.boot.databases.ITable") }

        return builder.buildMethod()
    }

    fun getId(): JcMethod {
        return JcMethodBuilder(clazz)
            .setName("\$getId").addBlanckAnnot(GET_ID_ANNOT)
            .setDesc("()L${classTable.idColumn.type.internalDesc};")
            .addFillerFuture(JcGetIdTransformer(classTable))
            .buildMethod()
    }

    fun getSerializer(): JcMethod {
        return JcMethodBuilder(clazz)
            .setName("\$serialize").addBlanckAnnot(SERIALIZER_ANNOT)
            .setDesc("()[Ljava/lang/Object;")
            .addFillerFuture(JcSerializerTransformer(classTable))
            .buildMethod()
    }

    fun getIdentity(): JcMethod {
        val classType = clazz.toType()
        val clasDesc = classType.typeName.jvmName()
        return JcMethodBuilder(clazz)
            .setName("\$identity").addBlanckAnnot(IDENTITY_ANNOT)
            .setDesc("($clasDesc)$clasDesc")
            .addFillerFuture(JcIdentityTransformer(classType))
            .addFreshParam(clazz.name)
            .buildMethod()
    }

    fun getLambdas(): List<JcMethod> {
        return classTable.relations.flatMap { rel ->
            val subTable = collector.findSubTable(rel.origField)!!
            val btwTable = when (rel) {
                is Relation.RelationByTable -> rel.joinTable.name
                else -> null
            }?.let { collector.getBtwTable(it) }

            val gen = SubSignatureGenerator(cp, classTable, subTable, btwTable, rel, clazz)
            val lambdas = if (rel is Relation.RelationByTable) {
                gen.getByTableLambdas()
            } else {
                listOf(gen.getFilter())
            }

            lambdas.also { JcDataclassTransformer.addRelatedLambdas(clazz, rel.origField, it) }
        }
    }

    private class SubSignatureGenerator(
        val cp: JcClasspath,
        val classTable: TableInfo.TableWithIdInfo,
        val subTable: TableInfo.TableWithIdInfo,
        val btwTable: TableInfo?,
        val rel: Relation,
        val clazz: JcClassOrInterface
    ) {

        fun getByTableLambdas(): List<JcMethod> {
            return listOf(getBtwFilter(), getBtwSelector(), getSetFilter())
        }

        fun getFilter(): JcMethod {
            return JcMethodBuilder(clazz)
                .setName("\$${rel.origField.name}filter")
                .setDesc("(${rel.origField.type.typeName.jvmName()})Ljava/lang/Boolean;")
                .addBlanckAnnot(FILTER_ANNOT)
                .addFreshParam(rel.origField.type.typeName)
                .addFillerFuture(JcSubFilterTransformer(cp, classTable, subTable, btwTable, rel))
                .buildMethod()
        }

        fun getBtwFilter(): JcMethod {
            return JcMethodBuilder(clazz)
                .setName("\$${rel.origField.name}BetweenFilter")
                .setDesc("([Ljava/lang/Object;)Ljava/lang/Boolean;")
                .addBlanckAnnot(FILTER_BTW_ANNOT)
                .addFreshParam("java.lang.Object[]")
                .addFillerFuture(JcBtwFilterTransformer(cp, classTable, subTable, btwTable, rel))
                .buildMethod()
        }

        fun getBtwSelector(): JcMethod {
            return JcMethodBuilder(clazz)
                .setName("\$${rel.origField.name}BetweenSelector")
                .setDesc("([Ljava/lang/Object;)L${subTable.idColumn.type.internalDesc};")
                .addBlanckAnnot(SELECT_BTW_ANNOT)
                .addFreshParam("java.lang.Object[]")
                .addFillerFuture(JcBtwSelectTransformer(cp, classTable, subTable, btwTable, rel))
                .buildMethod()
        }

        fun getSetFilter(): JcMethod {
            return JcMethodBuilder(clazz)
                .setName("\$${rel.origField.name}SetFilter")
                .setDesc("(${subTable.origClass.jvmDescriptor})Ljava/lang/Boolean;")
                .addBlanckAnnot(FILTER_SET_ANNOT)
                .addFreshParam(rel.origField.type.typeName)
                .addFillerFuture(JcSetFilterTransformer(cp, classTable, subTable, btwTable, rel))
                .buildMethod()
        }
    }
}
