package org.usvm.machine.interpreter.transformers

import kotlinx.collections.immutable.toPersistentList
import org.jacodb.api.jvm.JcClassExtFeature
import org.jacodb.api.jvm.JcClassOrInterface
import org.jacodb.api.jvm.JcClasspath
import org.jacodb.api.jvm.JcField
import org.jacodb.api.jvm.JcMethod
import org.jacodb.api.jvm.ext.findClass
import org.jacodb.api.jvm.ext.jvmName
import org.jacodb.impl.bytecode.JcFieldImpl
import org.jacodb.impl.bytecode.JcMethodImpl
import org.jacodb.impl.cfg.util.internalDesc
import org.jacodb.impl.features.JcFeaturesChain
import org.jacodb.impl.types.*
import org.usvm.machine.interpreter.JcDataclassLambdaTransformer
import org.usvm.util.JcTableInfoCollector
import org.usvm.util.Relation
import org.usvm.util.TableInfo
import org.usvm.util.blancAnnotation
import org.usvm.util.contains
import org.usvm.util.getSetFieldName
import org.usvm.util.jvmDescriptor

val JcClassOrInterface.isDataClass: Boolean get() = contains(annotations, "Entity")

const val INIT_ANNOT = "\$generatedInit"
const val GET_ID_ANNOT = "\$generatedGetId"
const val FILTER_ANNOT = "\$generatedFilter"
const val FILTER_BTW_ANNOT = "\$generatedBtwFilter"
const val SELECT_BTW_ANNOT = "\$generatedBtwSelector"
const val FILTER_SET_ANNOT = "\$generatedSetFilter"

object JcDataclassTransformer : JcClassExtFeature {

    // prevents cycles
    private val askedClasses : HashMap<String, MutableList<JcField>> = hashMapOf()
    // relation - generated by it field
    private val relationFields : HashMap<String, JcField> = hashMapOf()

    fun relatedField(clazz: JcClassOrInterface, rel : Relation) : JcField? {
        return combName(clazz, rel).let { relationFields[it] }
    }

    private fun combName(clazz : JcClassOrInterface, rel: Relation) : String {
        return "${clazz.name}\$${rel.origField.name}"
    }

    override fun fieldsOf(clazz: JcClassOrInterface, originalFields: List<JcField>): List<JcField>? {

        if (!clazz.isDataClass) return null
        if (askedClasses.contains(clazz.name)) return askedClasses[clazz.name]

        val fields = originalFields.toMutableList()
        askedClasses[clazz.name] = fields

        val cp = clazz.classpath
        val collector = JcTableInfoCollector(cp)
        val classTable = collector.collectTable(clazz)

        classTable.relations.forEach { rel ->

            val subTable = collector.findSubTable(rel)!!
            val subIdType = subTable.idColumn.type.typeName

            val field = if (rel is Relation.RelationByTable) {
                val fieldInfo = FieldInfo(
                    getSetFieldName(rel),
                    "Ljava/util/Set<${subIdType.jvmName()}>;",
                    2,
                    "Ljava.util.Set;",
                    listOf()
                )

                JcFieldImpl(rel.origField.enclosingClass, fieldInfo)
            }
            else {
                val fieldInfo = FieldInfo(
                    "\$${rel.origField.name}IdCheck",
                    null,
                    2,
                    "L${subIdType};",
                    listOf()
                )

                JcFieldImpl(clazz, fieldInfo)
            }

            relationFields[combName(clazz, rel)] = field
            fields.add(field)
        }

        return fields
    }

    override fun methodsOf(clazz: JcClassOrInterface, originalMethods: List<JcMethod>): List<JcMethod>? {

        if (!clazz.isDataClass) return null

        val cp = clazz.classpath
        val collector = JcTableInfoCollector(cp)
        val classTable = collector.collectTable(clazz)
        val gen = SignatureGenerator(cp, collector, classTable)

        val blancInit = gen.getConstructor()
        val getId = gen.getId()
        val lambdas = gen.getLambdas()

        return originalMethods + blancInit + getId + lambdas
    }
}

private class SignatureGenerator(
    val cp : JcClasspath,
    val collector : JcTableInfoCollector,
    val classTable : TableInfo.TableWithIdInfo
) {

    val clazz = classTable.origClass
    val pFeatures = cp.features!!.toPersistentList()

    fun getConstructor() : JcMethod {

        val newFeatures = pFeatures.add(0, JcGeneratedInitTransformer(classTable, collector))
        val relTables = collector.tables().filter { !it.name.equals(classTable.name) }

        val itableDesc = cp.findClass("generated.org.springframework.boot.databases.ITable").jvmDescriptor
        val desc = "([Ljava/lang/Object;${relTables.joinToString(separator = "") { itableDesc }})V"

        val signature = "([Ljava/lang/Object;${relTables.joinToString(separator = "") { info ->
            "${itableDesc}<${info.origClass.jvmDescriptor}>"
        }};)V"

        val parametrs = mutableListOf(
            ParameterInfo("java.lang.Object[]", 0, 1, "row", listOf())
        )

        relTables.forEachIndexed { ix, info ->
            val newParam = ParameterInfo(
                "generated.org.springframework.boot.databases.ITable",
                ix + 1,
                1,
                "${info.name}Condition",
                listOf()
            )

            parametrs.add(newParam)
        }

        val newMethodInfo = MethodInfo(
            "<init>",
            desc,
            signature,
            1,
            listOf(blancAnnotation(INIT_ANNOT)),
            listOf(),
            parametrs
        )
        val newInit = JcMethodImpl(newMethodInfo, JcFeaturesChain(newFeatures), classTable.origClass)

        return newInit
    }

    fun getId() : JcMethod {

        val newFeatures = pFeatures.add(0, JcGeneratedGetIdTransformer(classTable))

        val desc = "()L${classTable.idColumn.type.internalDesc};"

        val methodInfo = MethodInfo(
            "\$getId",
            desc,
            null,
            1,
            listOf(blancAnnotation(GET_ID_ANNOT)),
            listOf(),
            listOf()
        )
        val getId = JcMethodImpl(methodInfo, JcFeaturesChain(newFeatures), classTable.origClass)

        return getId
    }

    fun getLambdas() : List<JcMethod> {

        val methods = mutableListOf<JcMethod>()

        classTable.relations.forEach { rel ->

            val subTable = collector.findSubTable(rel)!!

            val btwTable = when (rel) {
                is Relation.RelationByTable -> rel.joinTable.name
                else -> null
            }?.let { collector.getBtwTable(it) }

            val newFeature = JcDataclassLambdaTransformer(cp, classTable, subTable, btwTable, rel)
            val newFeatures = JcFeaturesChain(pFeatures.add(0, newFeature))
            val gen = SubSignatureGenerator(rel, subTable, newFeatures, clazz)

            if (rel is Relation.RelationByTable) {
                methods.add(gen.getBtwFilter())
                methods.add(gen.getBtwSelector())
                methods.add(gen.getSetFilter())
            }
            else {
                methods.add(gen.getFilter())
            }
        }

        return methods
    }
}

private class SubSignatureGenerator(
    val rel : Relation,
    val subTable : TableInfo.TableWithIdInfo,
    val newFeatures : JcFeaturesChain,
    val clazz: JcClassOrInterface
) {

    fun getFilter() : JcMethod {
        val desc = "(${rel.origField.type.typeName.jvmName()})Ljava/lang/Boolean;"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}filter",
            desc,
            null,
            1,
            listOf(blancAnnotation(FILTER_ANNOT)),
            listOf(),
            listOf(ParameterInfo(rel.origField.type.typeName, 0, 1, "subc", listOf()))
        )

        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }

    fun getBtwFilter() : JcMethod {
        val desc = "([Ljava/lang/Object;)Ljava/lang/Boolean;"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}BetweenFilter",
            desc,
            null,
            1,
            listOf(blancAnnotation(FILTER_BTW_ANNOT)),
            listOf(),
            listOf(ParameterInfo("java.lang.Object[]", 0, 1, "row", listOf()))
        )
        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }

    fun getBtwSelector() : JcMethod {
        val desc = "([Ljava/lang/Object;)L${subTable.idColumn.type.internalDesc};"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}BetweenSelector",
            desc,
            null,
            1,
            listOf(blancAnnotation(SELECT_BTW_ANNOT)),
            listOf(),
            listOf(ParameterInfo("java.lang.Object[]", 0, 1, "row", listOf()))
        )

        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }

    fun getSetFilter() : JcMethod {
        val desc = "(${subTable.origClass.jvmDescriptor})Ljava/lang/Boolean;"
        val methodInfo = MethodInfo(
            "\$${rel.origField.name}SetFilter",
            desc,
            null,
            1,
            listOf(blancAnnotation(FILTER_SET_ANNOT)),
            listOf(),
            listOf(ParameterInfo(rel.origField.type.typeName, 0, 1, "subc", listOf()))
        )

        return JcMethodImpl(methodInfo, newFeatures, clazz)
    }
}
