package org.usvm.machine.interpreter.transformers

import org.jacodb.api.jvm.JcMethod
import org.jacodb.api.jvm.JcMethodExtFeature
import org.jacodb.api.jvm.cfg.JcAssignInst
import org.jacodb.api.jvm.cfg.JcFieldRef
import org.jacodb.api.jvm.cfg.JcReturnInst
import org.jacodb.api.jvm.cfg.JcThis
import org.jacodb.api.jvm.ext.toType
import org.jacodb.impl.cfg.JcInstListImpl
import org.jacodb.impl.cfg.JcInstLocationImpl
import org.jacodb.impl.features.classpaths.AbstractJcInstResult
import org.jacodb.impl.types.JcTypedFieldImpl
import org.jacodb.impl.types.substition.JcSubstitutorImpl
import org.usvm.instrumentation.util.toJcType
import org.usvm.instrumentation.util.typename
import org.usvm.machine.interpreter.transformers.JcSingleInstructionTransformer.BlockGenerationContext
import org.usvm.util.TableInfo
import org.usvm.util.contains

val JcMethod.generatedGetId : Boolean get() = contains(this.annotations, GET_ID_ANNOT)

// Integer $getId() { return id; }
class JcGeneratedGetIdTransformer(
    val classTable : TableInfo
) : JcMethodExtFeature {

    override fun instList(method: JcMethod): JcMethodExtFeature.JcInstListResult? {

        if (!method.generatedGetId) return null

        val template = JcReturnInst(JcInstLocationImpl(method, 0, 0), null)
        val transformer = JcSingleInstructionTransformer(JcInstListImpl(listOf(template)))

        transformer.generateReplacementBlock(template) { generateBody() }

        // removes generated by transformer gotos
        val inst = transformer.buildInstList().toMutableList()
        inst.remove(inst[0])
        inst.remove(inst.last())

        return AbstractJcInstResult.JcInstListResultImpl(method, JcInstListImpl(inst.toList()))
    }

    private fun BlockGenerationContext.generateBody() {

        val clazz = classTable.origClass!!
        val cp = clazz.classpath
        val classType = clazz.typename.toJcType(cp)!!
        val idType = classTable.idColumn!!.type.toJcType(cp)!!

        val lhv = nextLocalVar("%0", idType)
        val rhv = JcFieldRef(JcThis(classType), JcTypedFieldImpl(
            clazz.toType(),
            classTable.idField!!,
            JcSubstitutorImpl()
        ))
        addInstruction { loc -> JcAssignInst(loc, lhv, rhv) }

        addInstruction { loc -> JcReturnInst(loc, lhv) }
    }
}
